version: "3.8"

networks:
  share-net:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 1s
      retries: 20
    networks:
      - share-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - share-net

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: npm run start:dev gateway
    container_name: gateway
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: on-failure:5
    links: 
      - mongodb
      - rabbitmq
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - share-net

  service-stock:
    build:
      context: .
      dockerfile: ./apps/service-stock/Dockerfile
    command: npm run start:dev service-stock
    container_name: service-stock
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: on-failure:5
    links: 
      - mongodb
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - share-net

